config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  devise_for :users
  root 'pages#index'
  get 'pages/index'
  resources :reservations, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :employees, only: [:index]
  resources :bicycles, only: [:index, :new, :create, :edit, :update, :destroy] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
    has_many :reservations, dependent: :destroy
    has_many :employees, through: :reservations
  end
  

app/models/employee.rb
class Employee < ApplicationRecord
    #Kad tiek izveidots lietotājs, tiek arī izveidots attiecīgais darbinieka objekts
    belongs_to :user
    has_many :reservations, dependent: :destroy
    has_many :bicycles, through: :reservations
    validates :name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true
  end
  

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :employee
  belongs_to :bicycle
  validates :start_time, :end_time, presence: true
  validate :end_time_after_start_time
  validate :no_overlapping_reservations

  scope :expired, -> { where("end_time < ?", Time.current) }

  def self.delete_expired_reservations
    Rails.logger.info "Deleting expired reservations at #{Time.current}"
    expired_reservations = expired
    expired_reservations.each do |reservation|
      Rails.logger.info "Checking reservation #{reservation.id} with end_time #{reservation.end_time}"
    end
    Rails.logger.info "Found #{expired_reservations.count} expired reservations"
    expired_reservations.destroy_all
  end
  private


  def end_time_after_start_time
    if end_time.present? && start_time.present?
      errors.add(:end_time, "Beigu laiks nevar būt pirms sākuma") if end_time <= start_time
    end
  end

  def no_overlapping_reservations
    if Reservation.where(bicycle_id: bicycle_id)
                  .where.not(id: id)
                  .where('start_time < ? AND end_time > ?', end_time, start_time)
                  .exists?
      errors.add(:base, 'Šis velosipēds sajā laika posmā ir jau rezervēts.')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :reservations, dependent: :destroy # Ja lietotājs tiek dzēsts, tad tiek dzēstas visas rezervācijas
  has_one :employee, dependent: :destroy # Ja lietotājs tiek dzēsts, tad tiek dzēsta arī darbinieks

  after_create :create_employee_record # Pēc lietotāja izveidošanas tiek izveidots arī darbinieks

  private

  def create_employee_record
    self.create_employee(name: self.name, last_name: self.last_name, email: self.email) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    private
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name, :email])
    end
  end
  

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :authenticate_user!
  def index
    @bicycles = Bicycle.all
  end

  def new
    @bicycle = Bicycle.new
  end

  def create
    @bicycle = Bicycle.new(bicycle_params)
    if @bicycle.save
      redirect_to bicycles_path
    else
      render :new
    end
  end

  def edit
    @bicycle = Bicycle.find(params[:id])
  end

  def update

    @bicycle = Bicycle.find(params[:id])
    if @bicycle.update(bicycle_params)
      redirect_to bicycles_path
    else
      render :edit
    end
  end

  def destroy
    @bicycle = Bicycle.find(params[:id])
    @bicycle.destroy
    redirect_to bicycles_path
  end

  def show_reservation
    @bicycle = Bicycle.find(params[:id])
    @reservations = @bicycle.reservations 
    render json: { bicycle: @bicycle, reservations: @reservations }
  end

  private
  def bicycle_params
    params.require(:bicycle).permit(:name)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  def index
    @employees = Employee.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reservation, only: [:edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  def index
    @reservations = Reservation.all
    @bicycles = Bicycle.all
    @employees = Employee.all
  end

  def new
    @reservation = Reservation.new
    @bicycles = Bicycle.all
  end

  def create
    @reservation = current_user.employee.reservations.build(reservation_params)
    if @reservation.save
      redirect_to reservations_path, notice: 'Rezervācija izveidota.'
    else
      flash.now[:alert] = @reservation.errors.full_messages.join(", ") #kļūda, ja rezervāciju neizdevās saglabāt
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @bicycles = Bicycle.all
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to reservations_path, notice: 'Rezervācija atjaunināta.'
    else
      flash.now[:alert] = @reservation.errors.full_messages.join(", ")#kļūda, ja rezervāciju neizdevās rediģēt
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @reservation.destroy
    redirect_to reservations_path, notice: 'Rezervācija izdzēsta.'
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def authorize_user!
    unless @reservation.employee.user == current_user
      redirect_to reservations_path, alert: 'Tu neesi autorizēts lai rediģētu šo rezervāciju.'
    end
  end

  def reservation_params
    params.require(:reservation).permit(:bicycle_id, :start_time, :end_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/bicycles/edit.html.erb
<h1>Rediģēt velosipēdu</h1>
<%= form_with(model: @bicycle, url: bicycle_path(@bicycle), method: :patch, local: true) do |form| %>
  <% if @bicycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bicycle.errors.count, "error") %>Nav iespējams saglabāt objektu:</h2>
      <ul>
        <% @bicycle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Rediģēt', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Atpakaļ', bicycles_path, class: 'btn btn-secondary' %>

app/views/bicycles/index.html.erb
<h1 class="mb-4">Velosipēdi</h1>
<ul class="list-group">
  <% @bicycles.each do |bicycle| %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= bicycle.name %>
      <% if bicycle.reservations.any? %>
        <span class="badge bg-primary rounded-pill"><%= pluralize(bicycle.reservations.count, 'Rezrevācija') %></span>
      <% else %>
        <span class="badge bg-secondary rounded-pill">Nav rezervāciju</span>
      <% end %>
      <div class="btn-group" role="group" aria-label="Actions">
        <%= link_to 'Edit', edit_bicycle_path(bicycle), class: 'btn btn-secondary btn-sm' %>
        <%= button_to 'Dzēst', bicycle_path(bicycle), method: :delete, data: { turbo_confirm: 'Vai tiešām vēlaties dzēst šo Velosipēdu?' }, remote: true, class: 'btn btn-danger btn-sm' %>
      </div>
    </li>
  <% end %>
</ul>

<%= link_to 'Jauns velosipēds', new_bicycle_path, class: 'btn btn-primary mt-4' %>

app/views/bicycles/new.html.erb
<h1>Jauns Velosipēds</h1>
<%= form_with(model: @bicycle, url: bicycles_path, local: true) do |form| %>
  <% if @bicycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bicycle.errors.count, "error") %> Nav iespējams saglabāt objektu:</h2>

      <ul>
        <% @bicycle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Bicycle', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Atpakaļ', bicycles_path, class: 'btn btn-secondary' %>

app/views/employees/index.html.erb
<h1 class="mb-4">Darbinieki</h1>
<ul class="list-group">
  <% @employees.each do |employee| %>
    <li class="list-group-item">
      <strong><%= employee.name %> <%= employee.last_name %></strong> (<%= employee.email %>)
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>E-Bike</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= root_path %>">Ebike</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Darbinieki', employees_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Velosipēdi', bicycles_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Rezervācijas', reservations_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Jauna rezervācija', new_reservation_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Flash Messages -->
  <div id="flash-messages" class="container mt-3">
    <% flash.each do |key, message| %>
      <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="btn-close close-flash" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>

  <div class="container mt-3">
    <%= yield %>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const flashMessages = document.getElementById('flash-messages');
      if (flashMessages) {
        setTimeout(() => {
          flashMessages.style.display = 'none';
        }, 5000); // 5-second timer
      }

      // Close flash messages
      document.querySelectorAll('.close-flash').forEach(button => {
        button.addEventListener('click', () => {
          button.parentElement.style.display = 'none';
        });
      });
    });
  </script>
</body>
</html>

app/views/pages/index.html.erb
<% if user_signed_in? %>
  <h1 class="mb-4">Sveiki!, 
     <%= current_user.name %> <%= current_user.last_name %>, <%= current_user.email %></h1>
  <%= link_to 'Iziet no profila', destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-danger' %>
<% else %>
  <h1 class="mb-4">Mājas</h1>
  <%= link_to 'Autorizēties', new_user_session_path, class: 'btn btn-primary' %>
<% end %>

app/views/reservations/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Reservations#create</h1>
  <p>Find me in app/views/reservations/create.html.erb</p>
</div>

app/views/reservations/edit.html.erb
<h1 class="mb-4">Rediģēt rezervāciju</h1>

<%= form_with(model: @reservation, local: true, method: :patch, html: { class: 'needs-validation', novalidate: true }) do |form| %>
  <div class="mb-3">
    <%= form.label :bicycle_id, "Elektro velosipeds", class: 'form-label' %>
    <%= form.collection_select :bicycle_id, @bicycles, :id, :name, {}, { class: 'form-select', required: true } %>
    <div class="invalid-feedback">Lūdzu izvēlieties elektro velosipēdu.</div>
  </div>

  <div class="mb-3">
    <%= form.label :start_time, "Rezervācijas sākuma laiks", class: 'form-label' %>
    <%= form.datetime_local_field :start_time, value: @reservation.start_time.strftime("%Y-%m-%dT%H:%M"), min: Time.now.strftime("%Y-%m-%dT%H:%M"), max: Time.now.end_of_year.strftime("%Y-%m-%dT%H:%M"), class: 'form-control', required: true %>
    <div class="invalid-feedback">Lūdzu izvēlieties rezervācijas sākuma laiku.</div>
  </div>

  <div class="mb-3">
    <%= form.label :end_time, "Rezervācijas beigu laiks", class: 'form-label' %>
    <%= form.datetime_local_field :end_time, value: @reservation.end_time.strftime("%Y-%m-%dT%H:%M"), min: Time.now.strftime("%Y-%m-%dT%H:%M"), max: Time.now.end_of_year.strftime("%Y-%m-%dT%H:%M"), class: 'form-control', required: true %>
    <div class="invalid-feedback">Lūdzu izvēlieties rezervācijas beigu laiku.</div>
  </div>

  <div class="mb-3">
    <%= form.submit "Veikt izmaiņas", class: 'btn btn-primary' %>
    <%= link_to 'Atpakaļ', reservations_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

<!-- Konteineris priekš flash message -->
<div id="flash-messages" class="container mt-3">
  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close close-flash" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

<!-- Tiek noņemtas sekundes un milisekundes, tiek atrasts laiks tagad, lai varētu noteikt esošo gadu, 
jo lietotājam nav atļauts atzīmet pagātnes datumu vai citu gadu kāds ir tagad -->
<script>
  document.addEventListener('DOMContentLoaded', () => {
    const now = new Date().toISOString().slice(0, 16);
    const endOfYear = new Date(new Date().getFullYear(), 11, 31, 23, 59).toISOString().slice(0, 16);

    const startTimeInput = document.querySelector('input[name="reservation[start_time]"]');
    const endTimeInput = document.querySelector('input[name="reservation[end_time]"]');

    startTimeInput.setAttribute('min', now);
    startTimeInput.setAttribute('max', endOfYear);
    endTimeInput.setAttribute('min', now);
    endTimeInput.setAttribute('max', endOfYear);

    startTimeInput.addEventListener('input', (event) => {
      const selectedDate = new Date(event.target.value);
      if (selectedDate < new Date()) {
        alert('Lūdzu, izvēlieties nākotnes datumu.');
        event.target.value = '';
      }
    });

    endTimeInput.addEventListener('input', (event) => {
      const selectedDate = new Date(event.target.value);
      if (selectedDate < new Date()) {
        alert('Lūdzu, izvēlieties nākotnes datumu.');
        event.target.value = '';
      }
    });
  });
</script>

app/views/reservations/index.html.erb
<h1 class="mb-4">Visas rezervācijas</h1>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Darbinieki</th>
      <th>Velosipēds</th>
      <th>Rezervācijas sākums</th>
      <th>Rezervācijas beigas</th>
      <th>Darbības</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.employee.name %> <%= reservation.employee.last_name %></td>
        <td><%= reservation.bicycle.name %></td>
        <td><%= reservation.start_time %></td>
        <td><%= reservation.end_time %></td>
        <td>
          <% if reservation.employee.user == current_user %>
            <%= link_to 'Rediģēt', edit_reservation_path(reservation), class: 'btn btn-primary btn-sm' %>
            <%= button_to 'Dzēst', reservation_path(reservation), method: :delete, data: { turbo_confirm: 'Vai tiešām vēlaties dzēst šo rezervāciju?' }, remote: true, class: 'btn btn-danger btn-sm' %>
          <% else %>
            <span class="text-muted">Darbības pieejamas tikai rezervācijas veidotājam</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Jauna rezervācija', new_reservation_path, class: 'btn btn-success' %>

app/views/reservations/new.html.erb
<h1 class="mb-4">Jauna rezervācija</h1>

<%= form_with model: @reservation, local: true, html: { class: 'needs-validation', novalidate: true } do |form| %>
  <div class="mb-3">
    <%= form.label :bicycle_id, "Elektro velosipeds", class: 'form-label' %>
    <%= form.collection_select :bicycle_id, Bicycle.all, :id, :name, {}, { class: 'form-select', required: true } %>
    <div class="invalid-feedback">Lūdzu izvēlieties elektro velosipēdu.</div>
  </div>
  <div class="mb-3">
    <%= form.label :start_time, "Rezervācijas sākuma laiks", class: 'form-label' %>
    <%= form.datetime_local_field :start_time, min: Time.now.strftime("%Y-%m-%dT%H:%M"), max: Time.now.end_of_year.strftime("%Y-%m-%dT%H:%M"), class: 'form-control', required: true %>
    <div class="invalid-feedback">Lūdzu izvēlieties rezervācijas sākuma laiku.</div>
  </div>
  <div class="mb-3">
    <%= form.label :end_time, "Rezervācijas beigu laiks", class: 'form-label' %>
    <%= form.datetime_local_field :end_time, min: Time.now.strftime("%Y-%m-%dT%H:%M"), max: Time.now.end_of_year.strftime("%Y-%m-%dT%H:%M"), class: 'form-control', required: true %>
    <div class="invalid-feedback">Lūdzu izvēlieties rezervācijas beigu laiku.</div>
  </div>
  <%= form.hidden_field :employee_id, value: current_user.employee.id %>
  <div class="mb-3">
    <%= form.submit "Izveidot rezervāciju", class: 'btn btn-primary' %>
  </div>
<% end %>

<!-- Flash Messages Container -->
<div id="flash-messages" class="container mt-3">
  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close close-flash" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

<!-- Tiek noņemtas sekundes un milisekundes, tiek atrasts laiks tagad, lai varētu noteikt esošo gadu, 
jo lietotājam nav atļauts atzīmet pagātnes datumu vai citu gadu kāds ir tagad -->
<script>
  document.addEventListener('DOMContentLoaded', () => {
    const now = new Date().toISOString().slice(0, 16);
    const endOfYear = new Date(new Date().getFullYear(), 11, 31, 23, 59).toISOString().slice(0, 16);

    const startTimeInput = document.querySelector('input[name="reservation[start_time]"]');
    const endTimeInput = document.querySelector('input[name="reservation[end_time]"]');

    startTimeInput.setAttribute('min', now);
    startTimeInput.setAttribute('max', endOfYear);
    endTimeInput.setAttribute('min', now);
    endTimeInput.setAttribute('max', endOfYear);

    startTimeInput.addEventListener('input', (event) => {
      const selectedDate = new Date(event.target.value);
      if (selectedDate < new Date()) {
        alert('Lūdzu, izvēlieties nākotnes datumu.');
        event.target.value = '';
      }
    });

    endTimeInput.addEventListener('input', (event) => {
      const selectedDate = new Date(event.target.value);
      if (selectedDate < new Date()) {
        alert('Lūdzu, izvēlieties nākotnes datumu.');
        event.target.value = '';
      }
    });
  });
</script>